name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4
      
      # Set up Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      # Install client dependencies and run tests
      - name: Install client dependencies
        run: npm install
        working-directory: ./client
        
      - name: Run client tests
        run: npm test
        working-directory: ./client

      # Install server dependencies
      - name: Install server dependencies
        run: npm install
        working-directory: ./server
      


